@Statistic_HostAddress = http://localhost:5136

GET https://localhost:44362/statistics

###
POST https://localhost:44362/statistics
Content-Type: application/json
{
    "_id": "dfgvhjnkmjhugofrtg",
    "name": "Ivan Ivanov",
    "startTime": "1980-01-02T00:00:00.000Z",
    "endTime": "1980-01-04T00:00:00.000Z",
    "version": "1.0.6"
}